@echo off
if "%1"=="" (echo Usage: %~n0 file && exit /b)
powershell -Command "(gc %1.bat) -replace '::', '#' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '%', '$' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '/', '-' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '\', '/' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '==', '=' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '!==!', '!=' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '|', '|' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '@', 'set +v' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '*', '*' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '>', '>' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '>>', '>>' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '<', '<' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '%var%', '$var' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'rem', '#' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'not', '!' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'nul', '/dev/null' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'echo', 'echo' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'echo.', 'echo.' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'echo off', 'set +v' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'for %%var in (list) do', 'for var in [list]; do' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace ':label', '' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'goto', '' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'pause', 'sleep' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'choice', 'case or select' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'if', 'if' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'if exist filename', 'if [-e filename]' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'if !%n==!', 'if [-z "$N"]' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'call', 'source or .' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'command /c', 'source or .' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'set', 'export' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'shift', 'shift' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'sgn', '-It or -gt' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'errorlevel', '$?' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'con', 'stdin' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'prn', '/dev/lp0' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'lpt1', '/dev/lp0' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'com1', '/dev/ttyS0' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'assign', 'In' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'attrib', 'chmod' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'cd', 'cd' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'chdir', 'cd' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'cls', 'clear' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'comp', 'diff, comm, cmp' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'copy', 'cp' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'ctl-c', 'Ctl-C' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'ctl-z', 'Ctl-Z' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'del', 'rm' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'deltree', 'rm -rf' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'dir', 'ls -l' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'erase', 'rm' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'exit', 'exit' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'fc', 'comm, cmp' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'find', 'grep' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'findstr', 'grep' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'md', 'mkdir' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'mkdir', 'mkdir' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'more', 'more' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'move', 'mv' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'path', '$path' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'ren', 'mv' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'rename', 'mv' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'rd', 'rmdir' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'rmdir', 'rmdir' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'sort', 'sort' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'time', 'date' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'type', 'cat' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'xcopy', 'cp' | Out-File -encoding ASCII %1.sh"
::CAPSLOCK
powershell -Command "(gc %1.bat) -replace '::', '#' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '%', '$' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '/', '-' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '\', '/' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '==', '=' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '!==!', '!=' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '|', '|' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '@', 'set +v' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '*', '*' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '>', '>' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '>>', '>>' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '<', '<' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace '%VAR%', '$VAR' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'REM', '#' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'NOT', '!' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'NUL', '/dev/null' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'ECHO', 'echo' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'ECHO.', 'echo.' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'ECHO OFF', 'set +v' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'FOR %%VAR IN (LIST) DO', 'for var in [list]; do' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace ':LABEL', '' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'GOTO', '' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'PAUSE', 'sleep' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'CHOICE', 'case or select' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'IF', 'if' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'IF EXIST FILENAME', 'if [-e filename]' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'IF !%n==!', 'if [-z "$N"]' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'CALL', 'source or .' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'COMMAND /C', 'source or .' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'SET', 'export' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'SHIFT', 'shift' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'SGN', '-It or -gt' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'ERRORLEVEL', '$?' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'CON', 'stdin' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'PRN', '/dev/lp0' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'LPT1', '/dev/lp0' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'COM1', '/dev/ttyS0' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'ASSIGN', 'In' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'ATTRIB', 'chmod' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'CD', 'cd' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'CHDIR', 'cd' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'CLS', 'clear' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'COMP', 'diff, comm, cmp' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'COPY', 'cp' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'Ctl-C', 'Ctl-C' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'Ctl-Z', 'Ctl-Z' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'DEL', 'rm' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'DELTREE', 'rm -rf' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'DIR', 'ls -l' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'ERASE', 'rm' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'EXIT', 'exit' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'FC', 'comm, cmp' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'FIND', 'grep' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'FINDSTR', 'grep' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'MD', 'mkdir' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'MKDIR', 'mkdir' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'MORE', 'more' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'MOVE', 'mv' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'PATH', '$path' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'REN', 'mv' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'RENAME', 'mv' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'RD', 'rmdir' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'RMDIR', 'rmdir' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'SORT', 'sort' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'TIME', 'date' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'TYPE', 'cat' | Out-File -encoding ASCII %1.sh"
powershell -Command "(gc %1.bat) -replace 'XCOPY', 'cp' | Out-File -encoding ASCII %1.sh"
echo Coversion termined. Please check the file, this is a beta and it can also not work.
echo %1.bat was converted in %1.sh.
pause >nul
@echo on
exit